# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
    skip: [next-lint]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        args: ['--write', '--config', './.prettierrc']
        files: \.js$
  - repo: local
    hooks:
      - id: next-lint
        name: next-lint
        language: system
        entry: sh -c 'npm run lint-fix'
        files: \.js$
